apiVersion: v2
name: my-nginx-website
description: Wrapper chart per il deploy di Nginx
type: application
version: 1.0.0
appVersion: "1.25.0"

dependencies:
  - name: nginx
    version: 15.4.0  # Assicurati di usare una versione valida del chart
    repository: https://charts.bitnami.com/bitnami
