# Configurazione globale per il sotto-chart "nginx"
nginx:
  image:
    repository: bitnami/nginx
    tag: 1.25.3-debian-11-r0
  
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    path: /
    pathType: ImplementationSpecific
