apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkwarden-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # opzionale: limiti CIDR in ingresso
    # alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    # opzionale: specificare le porte listener (di default HTTP 80)
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  rules:
  - host: linkwarden.example.com   # o lascia vuoto se non ti serve l'host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkwarden-service
            port:
              number: 3000
