apiVersion: v1
kind: Service
metadata:
  name: linkwarden-service
  namespace: default
spec:
  selector:
    app: linkwarden
  ports:
  - name: name-of-service-port  
    protocol: TCP
    port: 3000
    targetPort: web-svc
  type: ClusterIP
