apiVersion: v1
kind: Service
metadata:
  name: linkwarden-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: linkwarden
  ports:
  - name: http
    protocol: TCP
    port: 30031       
    targetPort: 3000  
  type: ClusterIP
