apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkwarden-ingress
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: linkwarden.tuodominio.it  # <--- Aggiungi un host anche fittizio per test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkwarden-service
            port:
              number: 3000
